format = 1

[package]
id = "org.mochios.installer"
name = "Installer"
version = "0.1.0"
revision = 1
vendor = "mochiOS"
kind = "application"
architecture = "x86_64"
abi = "mochios-1"

[[binary]]
path = "/applications/Installer.app/entry.elf"
kind = "application"
requires = [
	"ipc.client",
	"ipc.server",
	"window.create",
]
